import Navbar from "@/components/Navbar";
import Footer from "@/components/footer";
import "./globals.css";

export const metadata = {
  title: "Stonners",
  description: "Generated by Stonners",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Navbar /> */}
        {children}
      {/* <Footer /> */}
      </body>
    </html>
  );
}
